spring:
  application:
    name: CatalogService
  cloud:
    gateway:
      routes:
        - id: catalog-route
          uri: http://localhost:8082
          predicates:
            - Path=/catalog/**

server:
  port: 8078

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

alex:
  dot: "local-property"


