spring:
  application:
    name: CatalogService
  cloud:
    gateway:
      routes:
        - id: catalog-route
          uri: http://localhost:8082
          predicates:
            - Path=/catalog/**
        - id: inventory-route
          uri: http://localhost:8083
          predicates:
            - Path=/inventory/**
        - id: products-route
          uri: http://localhost:8080
          predicates:
            - Path=/products/**

server:
  port: 8078

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

alex:
  dot: "local-property"


