spring:
  application:
    name: ProductService

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

reactive:
  feign:
    loadbalancer:
      enabled: false
    client:
      config:
        catalogFeignClient:
          options:
            readTimeoutMillis: 2000
            connectTimeoutMillis: 1000
        inventoryFeignClient:
          options:
            readTimeoutMillis: 2000
            connectTimeoutMillis: 1000

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      circuitBreakerId:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
  timelimiter:
    configs:
      default:
        timeoutDuration: 20s

alex:
  dot: "local-property"