server:
  port: 8079
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OleksandrMiroshnychenko/microservices-demo
          searchPaths: 'config-storage/{application}'
          default-label: master
          username: OleksandrMiroshnychenko
          password: 07aleksandrMir

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8078/eureka/